// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'back': string;
  'buttons': string;
  'count': string;
  'lose_text': string;
  'modal_hidden': string;
  'modal_visible': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
