// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'back': string;
  'checkBlock': string;
  'root': string;
  'scoreEl': string;
  'settings': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
