// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'header': string;
  'input': string;
  'label': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
